# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32bd346ee5d5e2a45a02bde7a8ca69542eb92105e3fa2a29ffc10bb53ad31eb435d5419f4ae184a16662597b63547fc7d192186e9aa4f48172cf09dc87de890

test:
  secret_key_base: 9054c819b458b9db6cb4415ff8ae328a90ceb4f0b3593434de708838dea43042df039ed5807834872161a74d758af10c5ecb9d5dda27731f7ba32281a77bfa20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
